import { personalInfo, socialLinks } from "../data";
import useParticles from "../hooks/useParticles";

const Contact = () => {
  useParticles(".contact-bg-particles");

  return (
    <section
      id="contact"
      className="py-24 bg-gradient-to-r from-indigo-600 to-amber-500 text-white relative overflow-hidden"
    >
      <div className="contact-bg-particles absolute top-0 left-0 w-full h-full overflow-hidden z-0">
        {/* Particles will be generated by useParticles hook */}
      </div>
      <div className="container mx-auto px-4 relative z-10">
        <div className="text-center mb-20">
          <h2
            className="text-4xl md:text-5xl font-bold mb-3 relative inline-block text-white after:content-[''] after:block after:absolute after:-bottom-3.5 after:left-1/2 after:-translate-x-1/2 after:w-24 after:h-1.5 after:bg-white/20 after:rounded-full"
            data-aos="fade-up"
          >
            Get In Touch
          </h2>
          <p
            className="text-white/80 mt-8 max-w-2xl mx-auto text-lg"
            data-aos="fade-up"
            data-aos-delay="100"
          >
            I'm always open to new opportunities and collaborations. Let's build
            something great together!
          </p>
        </div>

        <div className="flex flex-col md:flex-row gap-10 lg:gap-16 items-start">
          <div className="md:w-1/2" data-aos="fade-right" data-aos-delay="200">
            <h3 className="text-3xl font-semibold mb-8 flex items-center">
              <i className="fas fa-address-card text-amber-500 mr-4"></i>Contact
              Information
            </h3>
            <ul className="space-y-6">
              <ContactItem
                icon="fa-phone"
                label="Phone"
                value={personalInfo.phone}
                href={`tel:${personalInfo.phone}`}
              />
              <ContactItem
                icon="fa-envelope"
                label="Email"
                value={personalInfo.email}
                href={`mailto:${personalInfo.email}`}
              />
              <ContactItem
                icon="fa-map-marker-alt"
                label="Location"
                value={personalInfo.location}
                href="#"
              />
              <ContactItem
                icon="fab fa-github"
                label="GitHub"
                value={personalInfo.github.replace("https://", "")}
                href={personalInfo.github}
              />
            </ul>

            <div className="mt-12">
              <h4 className="text-2xl font-semibold mb-5">Follow Me</h4>
              <div className="flex space-x-4">
                {socialLinks.map((social, index) => (
                  <a
                    key={index}
                    href={social.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xl flex items-center justify-center w-11 h-11 rounded-full bg-white/10 text-white/80 hover:bg-amber-500 hover:text-white transition-all duration-300 transform hover:scale-110"
                    aria-label={social.platform}
                  >
                    <i className={social.icon}></i>
                  </a>
                ))}
              </div>
            </div>
          </div>

          <div
            className="md:w-1/2 bg-gradient-to-bl from-gray-900/70 via-gray-800/60 to-gray-900/70 backdrop-blur-lg rounded-2xl p-8 md:p-10"
            data-aos="fade-left"
            data-aos-delay="300"
          >
            <h3 className="text-3xl font-semibold mb-6 text-white">
              Send Me a Message
            </h3>
            <form className="space-y-5">
              <FloatingLabelInput id="name" type="text" label="Your Name" />
              <FloatingLabelInput id="email" type="email" label="Your Email" />
              <FloatingLabelInput id="subject" type="text" label="Subject" />
              <FloatingLabelTextarea id="message" label="Message" />

              <div>
                <button
                  type="submit"
                  className="bg-gradient-to-r from-indigo-600 to-amber-500 text-white font-semibold py-4 px-10 rounded-full shadow-lg hover:shadow-xl transition-all duration-300 ease-in-out flex items-center justify-center gap-2 w-full text-lg mt-2"
                >
                  <i className="fas fa-paper-plane mr-2"></i>Send Message
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
};

const ContactItem = ({ icon, label, value, href }) => (
  <li className="flex items-start group">
    <div className="w-12 h-12 rounded-xl bg-white/10 group-hover:bg-amber-500 flex items-center justify-center mr-5 text-xl text-amber-500 group-hover:text-white transition-all duration-300 shrink-0">
      <i className={`fas ${icon}`}></i>
    </div>
    <div>
      <p className="text-white/70 text-sm font-medium">{label}</p>
      <a
        href={href}
        target="_blank"
        rel="noopener noreferrer"
        className="text-lg hover:text-amber-500 transition-colors duration-200 break-all"
      >
        {value}
      </a>
    </div>
  </li>
);

const FloatingLabelInput = ({ id, type, label }) => (
  <div className="relative">
    <input
      type={type}
      id={id}
      name={id}
      placeholder=" "
      className="peer w-full bg-transparent border-b-2 border-gray-600 focus:border-amber-500 focus:outline-none pt-4 pb-2 text-white"
    />
    <label
      htmlFor={id}
      className="absolute left-0 top-0 text-amber-300 transition-all
               peer-placeholder-shown:top-2 peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400
               peer-focus:top-0 peer-focus:text-sm peer-focus:text-amber-500"
    >
      {label}
    </label>
  </div>
);

const FloatingLabelTextarea = ({ id, label }) => (
  <div className="relative">
    <textarea
      id={id}
      name={id}
      rows="5"
      placeholder=" "
      className="peer w-full bg-transparent border-b-2 border-gray-600 focus:border-amber-500 focus:outline-none pt-4 pb-2 text-white resize-none"
    ></textarea>
    <label
      htmlFor={id}
      className="absolute left-0 top-0 text-amber-300 transition-all
               peer-placeholder-shown:top-2 peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-400
               peer-focus:top-0 peer-focus:text-sm peer-focus:text-amber-500"
    >
      {label}
    </label>
  </div>
);

export default Contact;
